### ISSUE TITLE
Error in tests

### ISSUE THREAD

**Issue by cmsimike** [lmucs/wutup#1]
Tests in error: 
  creatingIncrementsSize(edu.lmu.cs.wutup.ws.dao.EventDaoTest)
  creatingDuplicateEventThrowsException(edu.lmu.cs.wutup.ws.dao.EventDaoTest): Unexpected exception, expected<edu.lmu.cs.wutup.ws.exception.EventExistsException> but was<java.lang.NullPointerException>
  eventAliceIsInInitialDataSet(edu.lmu.cs.wutup.ws.dao.EventDaoTest): PreparedStatementCallback; bad SQL grammar [select e._, u._ from event e join user u on (e.ownerId = u.id) where e.name=? limit ? offset ?]; nested exception is org.h2.jdbc.JdbcSQLException: Column "e.id" not found [42122-165]
  findingEventsViaPaginationWorks(edu.lmu.cs.wutup.ws.dao.EventDaoTest): PreparedStatementCallback; bad SQL grammar [select e._, u._ from event e join user u on (e.ownerId = u.id) limit ? offset ?]; nested exception is org.h2.jdbc.JdbcSQLException: Column "e.id" not found [42122-165]

**Comment by rtoal** [comment]
Thanks, Mike.  Fixed.
