### ISSUE TITLE
Event Occurrences GET method not working 

### ISSUE THREAD

**Issue by SaymV** [lmucs/wutup#2]
This:

> http://localhost:8080/wutup/occurrences?page=0&pageSize=20

Results in this:

> HTTP Status 415 - Unsupported Media Type

**Comment by rtoal** [comment]
It is not implemented yet.

On Oct 30, 2012, at 8:01 PM, Sam Verhasselt <notifications@github.com<mailto:notifications@github.com>>
 wrote:

This:

http://localhost:8080/wutup/occurences?page=0&pageSize=20

Results in this:

HTTP Status 404 - Not Found

**Comment by SaymV** [comment]
I accidentally misspelled occurrences, but it actually returns a 415.

On Tue, Oct 30, 2012 at 8:05 PM, Ray Toal notifications@github.com wrote:

> It is not implemented yet.
> 
> On Oct 30, 2012, at 8:01 PM, Sam Verhasselt <notifications@github.com
> <mailto:notifications@github.com>>
> wrote:
> 
> This:
> 
> http://localhost:8080/wutup/occurences?page=0&pageSize=20
> 
> Results in this:
> 
> HTTP Status 404 - Not Found
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/rtoal/wutup/issues/2>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rtoal/wutup/issues/2#issuecomment-9931274.

## 

Sam Verhasselt

8421 Gonzaga Ave

Los Angeles, CA

90045
My profiles: [image:
LinkedIn]http://www.linkedin.com/pub/sam-verhasselt/13/34/276

**Comment by rtoal** [comment]
Looking at the code for GET /occurrences, it looks like a mess.  They also don't yet seem to support finding without at least one query parameter other than pagination.  It should be pretty easy to patch.  I can get to it in another hour or so.

On Oct 30, 2012, at 8:06 PM, Sam Verhasselt <notifications@github.com<mailto:notifications@github.com>>
 wrote:

I accidentally misspelled occurrences, but it actually returns a 415.

On Tue, Oct 30, 2012 at 8:05 PM, Ray Toal <notifications@github.com<mailto:notifications@github.com>> wrote:

> It is not implemented yet.
> 
> On Oct 30, 2012, at 8:01 PM, Sam Verhasselt <notifications@github.com<mailto:notifications@github.com>
> mailto:notifications@github.com>
> wrote:
> 
> This:
> 
> http://localhost:8080/wutup/occurences?page=0&pageSize=20
> 
> Results in this:
> 
> HTTP Status 404 - Not Found
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/rtoal/wutup/issues/2>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rtoal/wutup/issues/2#issuecomment-9931274.

## 

Sam Verhasselt

8421 Gonzaga Ave

Los Angeles, CA

90045
My profiles: [image:
LinkedIn]http://www.linkedin.com/pub/sam-verhasselt/13/34/276

**Comment by SaymV** [comment]
I'm going to mark this closed, between Andy and Tyler's efforts, this has been resolved.
