### ISSUE TITLE
Webservice does not parse apostraphes in query parameters

### ISSUE THREAD

**Issue by SaymV** [lmucs/wutup#5]
When looking up a venue by name like this:
http://localhost:8080/wutup/venues?name=Sam's+House

I received the following error: 

```
Syntax error in SQL statement select v.* from venue v where lower(v.name) like lower('Sam's House%[*]') limit 20 offset 0; 
SQL statement:
select v.* from venue v where lower(v.name) like lower('Sam's House%') limit 20 offset 0 [42000-165]
```

This looks like we just have to parse the string and escape problematic characters before running the query.

**Comment by rowedonalde** [comment]
Oh, little Bobby Tables.

**Comment by rowedonalde** [comment]
http://localhost:8080/wutup/venues?name='%3Bdrop%20table%20users%3B

**Comment by rtoal** [comment]
We love you too, Don. :-)  At least you don't know where their production server is :)

**Comment by dondi** [comment]
I tracked the issue to `QueryBuilder`…the use of `StringBuilder` for setting parameters is what kills it.  Ironic, because I think they took this `QueryBuilder` from the `QueryBuilder` in [headmaster](https://github.com/dondi/headmaster)—but _that_ `QueryBuilder` turns the query string into a `Query` object first and _then_ sets the parameters of the query using `setParameter`.

**Comment by andyjwon** [comment]
I did a quick fix by just replacing every apostrophe with two, but I would love to know if there are any better ways to do this.

**Comment by rtoal** [comment]
Query parameters.

**Comment by dondi** [comment]
Look at how Hibernate does `setParameter`: [`AbstractQueryImpl`](http://javasourcecode.org/html/open-source/hibernate/hibernate-3.5.6-Final/org/hibernate/impl/AbstractQueryImpl.java.html), [`StringHelper`](http://javasourcecode.org/html/open-source/hibernate/hibernate-3.5.6-Final/org/hibernate/util/StringHelper.java.html).  JOOQ source code will probably have hints as well.
