### ISSUE TITLE
Posting Venue Name Same as Address

### ISSUE THREAD

**Issue by MarcMouallem** [lmucs/wutup#8]
When you post venues, it ignores the name and uses the address for both the name and address field. I think this happened when Tyler fixed the lat / long issue earlier today.

**Comment by andyjwon** [comment]
Should be resolved temporarily.

On Sat, Dec 8, 2012 at 1:18 AM, Marc Mouallem notifications@github.comwrote:

> When you post venues, it ignores the name and uses the address for both
> the name and address field. I think this happened when Tyler fixed the lat
> / long issue earlier today.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/rtoal/wutup/issues/8.

## 

Andrew Won
andyjwon@gmail.com

**Comment by MarcMouallem** [comment]
Thanks Andy!
